# Items that apply to ALL profiles:
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8011/eureka/,http://localhost:8012/eureka/,http://localhost:8013/eureka/
server:
  port: ${PORT:${SERVER_PORT:0}}   # Select any available port if neither port nor server port are specified.

---
spring:
  profiles: team
server:
  port: 8020  
pokemones: NoAplica
    
---
spring:
  profiles: agua
pokemones: Blastoise,Magikarp,Vaporeon
  
---
spring:
  profiles: fuego
pokemones: Chorizard,Vulpix,Magnar

---
spring:
  profiles: dragon
pokemones: Dratini,Dragonair,Dragonite

---
spring:
  profiles: hierba
pokemones: Venosor,Oddish,Bellsprout

---
spring:
  profiles: legendario
pokemones: articuno,zapdos,moltres,mew,mewtwo